image: 'rust:latest'

stages:
  - format
  - test
  - build
  - clippy
  - publish

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

test:
  stage: test
  script:
      - rustc --version
      - cargo --version
      - cargo test --verbose

build:
  stage: build
  script:
      - rustc --version
      - cargo --version
      - cargo build

format:
  stage: format
  script:
    - rustup component add rustfmt
    - cargo-fmt --all --verbose

clippy:
  stage: clippy
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings

publish:
  stage: publish
  only:
   - master
  script:
    - cargo publish --locked
  # we allow failure since it won't be able to publish a new package
  # when the version number has not been updated
  allow_failure: true

cache:
  paths:
    - apt/
    - cargo/
    - target/
