image: 'rust:latest'

stages:
  - format
  - test
  - build
  - clippy

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

test:
  stage: test
  script:
      - rustc --version
      - cargo --version
      - cargo test --verbose

build:
  stage: build
  script:
      - rustc --version
      - cargo --version
      - cargo build

format:
  stage: format
  script:
    - rustup component add rustfmt
    - cargo-fmt --all --verbose

clippy:
  stage: clippy
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings

cache:
  paths:
    - apt/
    - cargo/
    - target/
