[package]
name = "gtfs-geojson"
version = "0.1.0"
authors = ["N07070 <social@n07070.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

gtfs-structures = "0.19.1"
geojson = "0.18.0"
structopt = "0.3"
geo-types = "0.5.0"
serde_json = "1.0.50"
assert_approx_eq = "1.1.0"
